import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Calculadora from '../components/Calculadora'
import stylesmios from '../styles/mios.module.css'
import State from '../components/contexto'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <State>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={stylesmios.calcmain}>
        <Calculadora/>
      </div>
    </State>
  )
}
